version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      # - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-qwerty12345}
      - MONGO_INITDB_DATABASE=${DB_NAME:-library-netology}
  libnetology:
    build: .
    restart: always
    ports:
      - 3000:3001
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-qwerty12345}
      - DB_NAME=${DB_NAME:-library-netology}
      - DB_HOST=mongodb://mongo:27017
    depends_on:
      - mongo
